services:
  postgres:
    image: postgres:16
    container_name: card_management
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: card_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
